TEMPLATE = lib
CONFIG += static
CONFIG -= qt

DISTFILES += \
    ccsds/PacketTypes.acn \
    ccsds/PacketTypes.asn1 \
    ccsds/TC-Packet.acn \
    ccsds/TC-Packet.asn1 \
    ccsds/TM-Packet.acn \
    ccsds/TM-Packet.asn1 \
    common/ApplicationProcess.acn \
    common/ApplicationProcess.asn1 \
    common/BasicTypes.acn \
    common/BasicTypes.asn1 \
    common/ExecutionStep.acn \
    common/ExecutionStep.asn1 \
    common/meta.json \
    service-01/ErrorCodes.acn \
    service-01/ErrorCodes.asn1 \
    service-01/meta.json \
    service-01/PUS-1-10.acn \
    service-01/PUS-1-10.asn1 \
    service-01/PUS-1-1.acn \
    service-01/PUS-1-1.asn1 \
    service-01/PUS-1-2.acn \
    service-01/PUS-1-2.asn1 \
    service-01/PUS-1-3.acn \
    service-01/PUS-1-3.asn1 \
    service-01/PUS-1-4.acn \
    service-01/PUS-1-4.asn1 \
    service-01/PUS-1-5.acn \
    service-01/PUS-1-5.asn1 \
    service-01/PUS-1-6.acn \
    service-01/PUS-1-6.asn1 \
    service-01/PUS-1-7.acn \
    service-01/PUS-1-7.asn1 \
    service-01/PUS-1-8.acn \
    service-01/PUS-1-8.asn1 \
    service-09/meta.json \ 
    service-17/meta.json \
    service-17/PUS-17-1.acn \
    service-17/PUS-17-1.asn1 \
    service-17/PUS-17-2.acn \
    service-17/PUS-17-2.asn1 \
    service-17/PUS-17-3.acn \
    service-17/PUS-17-3.asn1 \
    service-17/PUS-17-4.acn \
    service-17/PUS-17-4.asn1 \
    ccsds/meta.json \
    ccsds/ApplicationProcessUser.acn \
    ccsds/ApplicationProcessUser.asn1 \
    ccsds/TM-Payload.asn1 \
    ccsds/TM-Payload.acn \
    ccsds/TC-Payload.acn \
    ccsds/TC-Payload.asn1 \
    service-01/Request.acn \
    service-01/Request.asn1 \
    service-03/meta.json \
    service-03/PUS-3-5-EnableThePeriodicGenerationOfHousekeepingReports.acn \
    service-03/PUS-3-5-EnableThePeriodicGenerationOfHousekeepingReports.asn1 \
    service-03/PUS-3-6-DisableThePeriodicGenerationOfHousekeepingParameterReport.acn \
    service-03/PUS-3-6-DisableThePeriodicGenerationOfHousekeepingParameterReport.asn1 \
    service-03/PUS-3-1-CreateAHousekeepingParameterReportStructure.acn \
    service-03/PUS-3-1-CreateAHousekeepingParameterReportStructure.asn1 \
    service-03/DiagnosticParameterReportStructure.acn \
    service-03/DiagnosticParameterReportStructure.asn1 \
    service-03/HousekeepingParameterReportStructure.acn \
    service-03/HousekeepingParameterReportStructure.asn1 \
    service-03/Parameter.acn \
    service-03/Parameter.asn1 \
    service-03/PUS-3-3-DeleteHousekeepingParameterReportStructures.acn \
    service-03/PUS-3-3-DeleteHousekeepingParameterReportStructures.asn1 \
    service-03/PUS-3-9-ReportHousekeepingParameterReportStructures.acn \
    service-03/PUS-3-9-ReportHousekeepingParameterReportStructures.asn1 \
    service-03/PUS-3-10-HousekeepingParameterReportStructureReport.acn \
    service-03/PUS-3-10-HousekeepingParameterReportStructureReport.asn1 \
    service-03/PeriodicGenerationActionStatus.acn \
    service-03/PeriodicGenerationActionStatus.asn1 \
    service-03/PUS-3-27-GenerateAOneShotReportForHousekeepingParameterReportStructures.acn \
    service-03/PUS-3-27-GenerateAOneShotReportForHousekeepingParameterReportStructures.asn1 \
    service-03/PUS-3-29-AppendParametersToAHousekeepingParameterReportStructure.acn \
    service-03/PUS-3-29-AppendParametersToAHousekeepingParameterReportStructure.asn1 \
    service-03/PUS-3-31-ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures.acn \
    service-03/PUS-3-31-ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures.asn1 \
    service-03/CollectionInterval.acn \
    service-03/CollectionInterval.asn1 \
    service-03/PUS-3-33-ReportThePeriodicGenerationPropertiesOfHousekeepingParameterReportStructures.acn \
    service-03/PUS-3-33-ReportThePeriodicGenerationPropertiesOfHousekeepingParameterReportStructures.asn1 \
    service-03/PUS-3-35-HousekeepingParameterReportPeriodicGenerationPropertiesReport.acn \
    service-03/PUS-3-35-HousekeepingParameterReportPeriodicGenerationPropertiesReport.asn1 \
    service-03/PUS-3-7-EnableThePeriodicGenerationOfDiagnosticParameterReports.acn \
    service-03/PUS-3-7-EnableThePeriodicGenerationOfDiagnosticParameterReports.asn1 \
    service-03/PUS-3-8-DisableThePeriodicGenerationOfDiagnosticParameterReports.acn \
    service-03/PUS-3-8-DisableThePeriodicGenerationOfDiagnosticParameterReports.asn1 \
    service-03/PUS-3-2-CreateADiagnosticParameterReportStructure.acn \
    service-03/PUS-3-2-CreateADiagnosticParameterReportStructure.asn1 \
    service-03/PUS-3-4-DeleteDiagnosticParameterReportStructures.acn \
    service-03/PUS-3-4-DeleteDiagnosticParameterReportStructures.asn1 \
    service-03/PUS-3-11-ReportDiagnosticParameterReportStructures.acn \
    service-03/PUS-3-11-ReportDiagnosticParameterReportStructures.asn1 \
    service-03/PUS-3-12-DiagnosticParameterReportStructureReport.acn \
    service-03/PUS-3-12-DiagnosticParameterReportStructureReport.asn1 \
    service-03/PUS-3-28-GenerateAOneShotReportForDiagnosticParameterReportStructures.acn \
    service-03/PUS-3-28-GenerateAOneShotReportForDiagnosticParameterReportStructures.asn1 \
    service-03/PUS-3-26-DiagnosticParameterReport.acn \
    service-03/PUS-3-26-DiagnosticParameterReport.asn1 \
    service-03/PUS-3-25-HousekeepingParameterReport.acn \
    service-03/PUS-3-25-HousekeepingParameterReport.asn1 \
    service-03/PUS-3-30-AppendParametersToADiagnosticParameterReportStructure.acn \
    service-03/PUS-3-30-AppendParametersToADiagnosticParameterReportStructure.asn1 \
    service-03/PUS-3-32-ModifyTheCollectionIntervalOfDiagnosticParameterReportStructures.acn \
    service-03/PUS-3-32-ModifyTheCollectionIntervalOfDiagnosticParameterReportStructures.asn1 \
    service-03/PUS-3-34-ReportThePeriodicGenerationPropertiesOfDiagnosticParameterReportStructures.acn \
    service-03/PUS-3-34-ReportThePeriodicGenerationPropertiesOfDiagnosticParameterReportStructures.asn1 \
    service-03/PUS-3-36-DiagnosticParameterReportPeriodicGenerationPropertiesReport.acn \
    service-03/PUS-3-36-DiagnosticParameterReportPeriodicGenerationPropertiesReport.asn1


include(.qmake/handleAsn1AcnBuild.pri)
