BasicTypes DEFINITIONS ::= BEGIN

PUSC-BOOL ::= BOOLEAN

PUSC-UINT ::= INTEGER (0 .. 9223372036854775807)--(0 .. 18446744073709551615) --max value not supported by asn1scc

PUSC-INT ::= INTEGER (-9223372036854775808 .. 9223372036854775807)

PUSC-REAL ::= REAL

PUSC-BIT-STRING ::= BIT STRING

PUSC-OCTET-STRING ::= OCTET STRING

PUSC-CHAR-STRING ::= IA5String

END

